### ISSUE TITLE
Feature Request: rename image after paste

### ISSUE THREAD

**Issue by pbolduc** [telesoho/vscode-markdown-paste-image#1]
I think a useful feature for your extension would be to be able to rename the pasted image by editing in markdown.  It will paste in with date/time file name and then be able to rename the image file and link in one go.

**Comment by telesoho** [comment]
Thank you very much for your suggestion, I will add this feature to the next version.

**Comment by telesoho** [comment]
Thank you for your suggestion, I will add this feature to the next version.

**Comment by knyzorg** [comment]
@telesoho This appears to be implemented and can be closed
