### ISSUE TITLE
Chinese will be convert to ? after pasting

### ISSUE THREAD

**Issue by MonkeyDAsce** [telesoho/vscode-markdown-paste-image#10]
Under Macosx 10.12.6
![image](https://user-images.githubusercontent.com/8073161/32564872-6eb05588-c4f0-11e7-8521-af8ccf8a4cff.png)
PS: 我看得懂中文

**Comment by telesoho** [comment]
@MonkeyDAsce
The extension use pbcopy and pdpaste command on IOS. You need to check pdpaste work fine on your MacOSX Terminal.

你能看懂中文最好了，按照下面文章的设定貌似能解决这个问题：
http://blog.vgod.tw/2008/01/09/%E5%9C%A8macosx-terminal%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%89%AA%E8%B2%BC%E7%B0%BF/

**Comment by telesoho** [comment]
@MonkeyDAsce 
The extension use pbcopy and pdpaste command on IOS. You need to check pdpaste work fine on your MacOSX Terminal.

你能看懂中文最好了，按照下面文章的设定貌似能解决这个问题：
http://blog.vgod.tw/2008/01/09/%E5%9C%A8macosx-terminal%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%89%AA%E8%B2%BC%E7%B0%BF/

**Comment by MonkeyDAsce** [comment]
![image](https://user-images.githubusercontent.com/8073161/32568955-b6166106-c4fa-11e7-953f-ac241bf46abb.png)

My pbcopy and pdpaste commands are OK, but my vscode didn't work.

**Comment by telesoho** [comment]
I found there is a bug report in [copy-paste](https://github.com/xavi-/node-copy-paste/issues/55), but it doesn't fixed yet.
The same problem has been found in other extension that use copy-paste.
[Chinese encoding problem when using mdmath.clipToHtml](https://github.com/goessner/mdmath/issues/13)

VS Code doesn't set "LC_CTYPE" environment variable.
> We won't fix this in VS Code because that fix would only work while developing an application that uses "clipboardy" inside VS Code. If this application is deployed (outside of VS Code) the fix would no longer be available and the application would fail. So it is the responsibility of the application to deal with the missing "LC_CTYPE" environment variable.

The more detail see:
[Microsoft/vscode#26502 (comment)](https://github.com/Microsoft/vscode/issues/26502#issuecomment-301043547)

May be I should use 'clipboardy' to replace 'copy-paste'.

**Comment by telesoho** [comment]
@MonkeyDAsce 
I have release a new version, Could you help me to check It work or not.

**Comment by MonkeyDAsce** [comment]
No, the new version doesn't work. It is the same as before.

**Comment by MonkeyDAsce** [comment]
Is there a problem? May your new version didn't  take effect. The extension always need "reload" no matter how many times I reload/restart VScode.
![image](https://user-images.githubusercontent.com/8073161/32656572-4f6e9758-c64d-11e7-9765-206ac9952de3.png)

**Comment by MonkeyDAsce** [comment]
Yeah, maybe it was my fault. The new version worked after I reinstalled the extension. Thank you very much!
