### ISSUE TITLE
Default name to be YYYY-MM-DD_HH-mm-ss_<selected text>

### ISSUE THREAD

**Issue by henrik-forsell** [telesoho/vscode-markdown-paste-image#105]
If I select a text then hit ctrl-alt-v the file will be named the selected name plus ".png".

I would like to be able to name the file to YYYY-MM-DD_HH-mm-ss_"selected text".png (without the quotation).

And also, would it be possible to have an option to add any selected text as the alt text?

E.g.
`![The selected text](../images/2023-02-28_07-29-59_The selected text.png)`

**Comment by henrik-forsell** [comment]
And, to make sure that the expected behaviour would be the same. Add an option e.g. "Append date to selected text".

**Comment by telesoho** [comment]
@henrik-forsell 
You can use predefine ${selectedText} to get current selected text in v0.21.0 now.
