### ISSUE TITLE
Custom filename format

### ISSUE THREAD

**Issue by Klepeto** [telesoho/vscode-markdown-paste-image#11]
It would be great to have option to change default filename of image.
Now I have to change it for every image...

**Comment by socay1** [comment]
[vscode-paste-image](https://github.com/mushanshitiancai/vscode-paste-image) have already done it.

**Comment by iaeiou** [comment]
Hi @Klepeto ,

some new features were added yesterday, maybe you wanna give a new try?

See: https://github.com/telesoho/vscode-markdown-paste-image#config
