### ISSUE TITLE
Add an option for set the name of the image

### ISSUE THREAD

**Issue by zjinc36** [telesoho/vscode-markdown-paste-image#122]
I hope to add an option that we can set the image name

![image](https://github.com/telesoho/vscode-markdown-paste-image/assets/33741027/4faf625b-9736-4a61-8d81-9bd23379f5a6)

**Comment by henrik-forsell** [comment]
There is a setting for this already, depending on what you want.
I have the following as the Name Base.
${datetime|yyyy-MM-DD_HH-mm-ss}${selectedText}

Example:
Select the text _Leading with data_
Paste the image and it comes out as:
![Leading with data](../images/2023-05-19_16-48-52Leading%20with%20data.png) 

(Actually, I tend to have a space before the text and select that too to get a nicer file name.)

I hope it would work for you.
