### ISSUE TITLE
How to customize the way HTML is converted to Markdown?

### ISSUE THREAD

**Issue by RoneoOrg** [telesoho/vscode-markdown-paste-image#124]
Hi there,

when pasting HTML into Vscode with Markdown Paste, titles are converted to

```
This is a title
-----------------
```

I would like to obtain
```
## This is a title
```

How can I change the default behavior?

**Comment by telesoho** [comment]
@RoneoOrg 

There are no way to customize.

**Comment by RoneoOrg** [comment]
> There are no way to customize.

Got it thanks!
