### ISSUE TITLE
Running the contributed command:''extension.MarkdownPaste' failed.

### ISSUE THREAD

**Issue by qqzzft** [telesoho/vscode-markdown-paste-image#13]
![snipaste20180421_111155](https://user-images.githubusercontent.com/7402209/39079845-fe7cb33e-4554-11e8-94da-a3e4f360fa5b.png)

extension version:0.7.4
vscode version:1.22.2 on windows

**Comment by telesoho** [comment]
Could you use the follow command to check  whether 'clipboard_i686.exe' and  'clipboard_x86_64.exe' exsit?

`dir %USERPROFILE%\.vscode\extensions\telesoho.vscode-markdown-paste-image-0.7.4\node_modules\clipboardy\fallbacks\windows`

If not, you need to reinstall this extension.

**Comment by chenxizhang** [comment]
same issue. I check the two file and both are exsit.
reinstall can not solve the issue too.

**Comment by telesoho** [comment]
May be there are some bug in  new version clipboardy, I have downgrade it to version 1.1.4.
Please reinstall this extension and check it work or not.

**Comment by chenxizhang** [comment]
it is work now @telesoho
