### ISSUE TITLE
command 'extension.markdownPaste' not found

### ISSUE THREAD

**Issue by byxs0x0** [telesoho/vscode-markdown-paste-image#16]
使用`ctrl+alt+v`快捷键出现了题目的错误信息！
尝试了[command 'extension.MarkdownPaste' not found #9](https://github.com/telesoho/vscode-markdown-paste-image/issues/9)的步骤：
1. `ctrl+shift+P`
2. `Markdown Paste`，发现能成功执行。

其中重新安装过，也检查过扩展
![image](https://user-images.githubusercontent.com/30452422/44034384-8f6b0af0-9f3f-11e8-846d-42a7984abf80.png)

都没有办法解决，以下是`VSCODE`版本信息
![image](https://user-images.githubusercontent.com/30452422/44034423-a434f31a-9f3f-11e8-819b-85b76a29211e.png)

**Comment by telesoho** [comment]
说明插件安装是没问题的，只是插件的名字已经改为telesoho.MarkdownPaste。很可能是你自定义了快捷键。
你可以试试下面的方法：
1. Ctrl+Shift+P，输入Open Keyboard Shortcuts File，打开快捷键定义文件
2. 查看用户自定义keybinding.json文件，查看ctrl+alt+v是否绑定到telesoho.MarkdownPaste命令上，如果不是请修改。
3. 如果自定义keybinding.json文件中没有对ctrl+alt+v的绑定，请检测左边的默认快捷键定义文件中的设定是否正确。
如图：
![image](https://user-images.githubusercontent.com/10979091/44039221-95ca773c-9f53-11e8-8907-eed40d0239c7.png)

**Comment by byxs0x0** [comment]
@telesoho 解决问题，很久以前自定义过快捷键，3q！
