### ISSUE TITLE
Paste rich text

### ISSUE THREAD

**Issue by dgk4201** [telesoho/vscode-markdown-paste-image#17]
I'd like to be able to paste rich text content and have it converted to md. Ulysses does this with a 'paste from' command. 

My workflow with Ulysses: I copy text from powerpoint containing bold, italic, emphasis, and lists and paste it into Ulysses using the 'paste from' feature. Ulysses converts the rich text to MD. I can then copy the MD formatted text to the clipboard as HTML to be pasted into an SQL document.

**Comment by telesoho** [comment]
Thank you for your suggestion, I will try to implement it.

**Comment by dgk4201** [comment]
Thanks. I think it will be great feature.

Regards,

Dan Kalagher
www.ixploreYellowstone.com

978-337-4201

**Comment by dgk4201** [comment]
BTW, I've installed xclip.

**Comment by telesoho** [comment]
@dgk4201 
I'm Sorry!
I have implemented the feature on Linux only, it does'nt work on Mac.
May be I should buy a Mac ...

**Comment by telesoho** [comment]
@dgk4201 
Could you select "Help\Toggle Developer Tools" to show javascript console panel, then use Ctrl+Alt+V to paste some rich text into a markdown, and send the console log to me? 

![image](https://user-images.githubusercontent.com/10979091/50268518-72c5f380-046e-11e9-8125-2c970b322e36.png)

**Comment by dgk4201** [comment]
Nothing happens. I'm on a pixelbook.
Here's the console:

[Extension Host] debugger listening on port 60649
extensionHost.ts:235 Extension Host
extensionHost.ts:236 Debugger listening on ws://
127.0.0.1:60649/ef5c97bc-2d6f-42d1-aa21-fc96a0285adb
For help see https://nodejs.org/en/docs/inspector

log.ts:157  INFO no standard startup: not running latest version
console.ts:134 [Extension Host] "vscode-markdown-paste" is now active!
3console.ts:134 [Extension Host] Clipboard Type: -1

Maybe it's xclip? Where should that be run? When?

Thanks for your help on this. I'd love to get this working.

Regards,

Dan Kalagher
https://www.iXploreNatureApps.com

**Comment by telesoho** [comment]
@dgk4201 
I think xclip work fine on your pixelbook. Maybe you copied content be not supported in this version.
This version of the extension does support "image/png","text/html" and "text/plain" only.
I want to know what content type of you copied. Could you please send me the output of teminal after 
 copying some rich content and runing the following command on your pixelbox terminal.  
`
source ~/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.11.0/res/linux_clipboard_content_type.sh
`

**Comment by dgk4201** [comment]
Here's the terminal output:

dankalagher@penguin:~$ source
~/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.11.0/res/linux_clipboard_content_type.sh
TIMESTAMP
TARGETS
UTF8_STRING
TEXT
dankalagher@penguin:~

Here's a screen shot of what I copied from PowerPoint:
[image: image.png]
When I do an ctrl-alt-v, I get nothing. A normal ctrl-v pastes a plain text
version.
Regards,

Dan Kalagher
https://www.iXploreNatureApps.com

**Comment by telesoho** [comment]
@dgk4201 
I'm so surprised while copy text from application on different linux will get different target type. 
I use ubuntu, I always get 'text/plain' content type while copy any text, so I use 'text/plain' to get clipboard text. It's the reason the extension doesn't work on your pixelbook.
`
text/plain;charset=utf-8
text/plain;charset=UTF-8
UTF-8
UTF8_STRING
COMPOUND_TEXT
STRING
application/x-openoffice-editengine;windows_formatname="EditEngineFormat"
text/richtext
MULTIPLE
`
I have to fix this issue first.
Thank you for your help.

**Comment by telesoho** [comment]
@dgk4201 
I want to know the clipboard content type on your pixelbook,
Could you help me to sent clipboard content target types of browser and powerpoint on your pixelbook to me?
You can use the following command to get clipboard content target types:

`xclip -selection clipboard -o -t TARGETS`

For example:
I copy some text from web browser Chrome, will get the following output by the command.
<pre>
TIMESTAMP
TARGETS
SAVE_TARGETS
MULTIPLE
STRING
UTF8_STRING
TEXT
text/html
text/plain
</pre>

When I copy some text from LibreOffice Impress, will get the following output by the command.
<pre>
text/plain;charset=utf-8
text/plain;charset=UTF-8
UTF-8
UTF8_STRING
COMPOUND_TEXT
STRING
application/x-openoffice-editengine;windows_formatname="EditEngineFormat"
text/richtext
MULTIPLE
</pre>

**Comment by dgk4201** [comment]
BTW, I just tried it on a Mac. Doesn't work. I get plan text. I must be
missing something on setup. What exactly do I need to do to set it up? How
do I use pbpaste?

Regards,

Dan Kalagher
https://www.iXploreNatureApps.com

**Comment by irvnriir** [comment]
Please add the feature for Windows (desc says it work fr linux)

**Comment by MadcowD** [comment]
Mac would be great @telesoho

**Comment by knyzorg** [comment]
@telesoho This appears to be implemented and can be closed
