### ISSUE TITLE
Paste Path add `./` and File name verification support for Chinese

### ISSUE THREAD

**Issue by revolveyao** [telesoho/vscode-markdown-paste-image#18]
There are times when you need to paste the path with `./`.To change it with `./`.
The file name may be in Chinese at some point.It is recommended that you change the regular expression that determines the file name's legitimacy.
```js
if (selectText && !/^[^\\/:\*\?""<>|]{1,120}$/.test(selectText)) {
            vscode.window.showInformationMessage('Your selection is not a valid file name!');
            return;
        }
```

**Comment by telesoho** [comment]
Thank you. I have fixed it.
