### ISSUE TITLE
variable ${fileBasename} not working

### ISSUE THREAD

**Issue by tyler2018** [telesoho/vscode-markdown-paste-image#19]
whether only support ${workspaceRoot}. 
usually need same folder and same article name as folder name.

**Comment by telesoho** [comment]
I have release ver 0.9.2 to support the following predefined variables

    - ${fileBasename} - the current opened file's basename
    - ${fileBasenameNoExtension} - the current opened file's basename with no file extension
    - ${fileExtname} - the current opened file's extension
    - ${fileDirname} - the current opened file's dirname
