### ISSUE TITLE
How to paste a local image file?

### ISSUE THREAD

**Issue by flyisland** [telesoho/vscode-markdown-paste-image#23]
I try to copy&paste a local image file and hope the link code would point to the existed local file, but it still asked me to create a new file.

**Comment by telesoho** [comment]
Could you please give me more information(os, steps ...)?

**Comment by flyisland** [comment]
1. copy a image file
![image](https://user-images.githubusercontent.com/547085/55547012-014f3f80-5703-11e9-992b-ef85c903c6c5.png)

2. press `Cmd+Alt+V`
![image](https://user-images.githubusercontent.com/547085/55547203-63a84000-5703-11e9-891b-de84900cf9bc.png)

This extension will ask for a file name to create a new file.

3. But since what I just copied is an `image file`, there is no image in the clipboard, this extension is unable to fulfill its job.
![image](https://user-images.githubusercontent.com/547085/55547351-b5e96100-5703-11e9-8137-c21f2a089bba.png)

**Comment by telesoho** [comment]
You should use 'Copy Path' instead of 'Copy'
@flyisland

**Comment by flyisland** [comment]
Got it, it works now, thanks!

**Comment by irvnriir** [comment]
<iframe src="https://onedrive.live.com/embed?cid=538295E3AB7B4EA4&resid=538295E3AB7B4EA4%21116&authkey=ANZIBboMRBxXAmU" width="320" height="257" frameborder="0" scrolling="no" allowfullscreen></iframe>

**Comment by irvnriir** [comment]
https://www.youtube.com/embed/47b_8jFcUE8
