### ISSUE TITLE
Can't  save the images to a default absolute path

### ISSUE THREAD

**Issue by tifDev** [telesoho/vscode-markdown-paste-image#28]
**I want all the pasted images to go into** "C:\Users\KWUIUN\Pictures\Img-repo" **without any prompt.**

I changed the settings on vscode and added this:
```
    "MarkdownPaste.path": "C:/Users/KWUIUN/Pictures/Img-repo/",
    "MarkdownPaste.silence": true,
```
But still asks for the filename of the picture and points to the current relative path of the working space.

How can i do this?

**Comment by iaeiou** [comment]
Hi @tifDev,

some new features were added yesterday, maybe you wanna give a new try?

See: https://github.com/telesoho/vscode-markdown-paste-image#config

**Comment by telesoho** [comment]
@tifDev 
It is working on ubuntu. May be your configure has been overwrited. 
See: #64
