### ISSUE TITLE
Error when saving image

### ISSUE THREAD

**Issue by jquintus** [telesoho/vscode-markdown-paste-image#3]
I've just installed the vscode markdown paste image plugin.  Whenever I try to use it I get an error:

> Make folder failed:c:/test/2017-05-21-00-25-39.png

Scrrenshot of the error below:

![image](https://cloud.githubusercontent.com/assets/641118/26281134/299c7e1a-3dbc-11e7-8301-6f6b202de956.png)

My trouble shoothing steps:

* I have access to the folder I'm trying to save the image into
* I've tried saving it to a folder that exists
* I've tried saving it to a sub-folder that does not exist
* I've tried saving it to the default folder suggested
* I've tried using it by pressing `ctrl-alt-v`
* I've tried using it by selecting `Markdown Paste Image` from the command bar (`ctrl-p`)
* Version 0.4.1 of the plugin
* Version 1.12.2 of VS Code

**Comment by telesoho** [comment]
@jquintus 
I got same error while try to save image into the first level sub folder that dost not exist of root folder (like:c:/test or c:/temp). I fixed the bug in 0.4.3, Could you please try this version on your machine? If it cannot fix your trouble, please give me more information about what's the OS and nodejs version on your machine.

**Comment by jquintus** [comment]
I just tested with 0.4.3 and it worked.  

Thanks for the quick response.

**Comment by jquintus** [comment]
ps.  Thanks for the plugin as well.  It's super helpful for me.

**Comment by telesoho** [comment]
I'm glad this tool can help you.
