### ISSUE TITLE
Provide an option to paste raw text.

### ISSUE THREAD

**Issue by AiRyunn** [telesoho/vscode-markdown-paste-image#31]
Since I want to totally replace the default paste command, I removed all rules, but it still try to convert it.

One case is when I copy & paste multiple lines, it will wrap the text.

Another case is copying url from chrome, it will convert to \<some url\>.

I hope it can provide an option to disable these features.

Thanks!

**Comment by telesoho** [comment]
If you  want to paste raw text, you  should use CTL+V.

**Comment by telesoho** [comment]
@espylapiza Sorry, I don’t really understand what you mean, can you give a concrete example?
