### ISSUE TITLE
Provide an option to change the 'cmd + shift + v' shortcut on MacOS

### ISSUE THREAD

**Issue by luszczynski** [telesoho/vscode-markdown-paste-image#33]
It would be nice if I could choose another shortcut to paste my image when working with markdown files. Currently cmd + shift + v is a shortcut for my clipboard manager so it is conflicting with this extension.

**Comment by telesoho** [comment]
You can modify keyboard shortcut for this extension as your like.

![image](https://user-images.githubusercontent.com/10979091/82796115-f845a280-9eaf-11ea-86e6-ffdab8a45038.png)

**Comment by luszczynski** [comment]
Thank you.
