### ISSUE TITLE
麻烦看下这几个问题

### ISSUE THREAD

**Issue by exam-ple** [telesoho/vscode-markdown-paste-image#34]
感谢您开发这么好的插件, 我不知道是我没操纵对, 还是本身没有这个功能, 麻烦看下

1. win系统下同时复制网页的文字和图片时, 只能粘贴到文字, 图片粘贴不上, 能不能弄个文字和图片可以一起复制的功能
2. win系统下本地图片可以用这个插件插入吗? 我看您有给一个issue回复说在mac下复制路径可以解决, 我在win下复制路径后粘贴的只是路径本身, 不会显示图片
3. 图片存储目录设置成中文名时会变成显示一段其它的码, 比如我设置成 "./图片" 时, 最终粘贴显示的是![20200602104324](https://user-images.githubusercontent.com/66286339/83474177-f1292080-a4bd-11ea-9be0-5e4184d55418.png)

感谢您抽空查看, 谢谢.

**Comment by telesoho** [comment]
> 感谢您开发这么好的插件, 我不知道是我没操纵对, 还是本身没有这个功能, 麻烦看下
> 
> 1. win系统下同时复制网页的文字和图片时, 只能粘贴到文字, 图片粘贴不上, 能不能弄个文字和图片可以一起复制的功能

目前不支持保存网页中图片的功能，将来也不计划加入这个功能．

> 2. win系统下本地图片可以用这个插件插入吗? 我看您有给一个issue回复说在mac下复制路径可以解决, 我在win下复制路径后粘贴的只是路径本身, 不会显示图片

如果是本地图片，插件不会拷贝本地图片到指定位置．但是，你可以通过拷贝图片的路径，然后用本插件的粘贴功能，将图片路径通过替换规则转换为markdown的图片链接．

> 3. 图片存储目录设置成中文名时会变成显示一段其它的码, 比如我设置成 "./图片" 时, 最终粘贴显示的是![20200602104324](https://user-images.githubusercontent.com/66286339/83474177-f1292080-a4bd-11ea-9be0-5e4184d55418.png)
> 

目前插件会把所有的中文都转换为URI编码，将来会提供不转换中文的版本．

> 感谢您抽空查看, 谢谢.

**Comment by PabloLION** [comment]
I think we can close this issue since they are all done?
