### ISSUE TITLE
Paste as base64 instead of local file link

### ISSUE THREAD

**Issue by lekoOwO** [telesoho/vscode-markdown-paste-image#36]
I'd like to ask for the mentioned feature, it'll be really great to embed the image in the markdown file!

we can do

```
... contents
![My Image][my_img]
...contents

[my_img]: data:image/png;base64,blahblahblahblah
```
By attaching the base64 on the end of file instead of inline it, it won't be ugly but still embed in file.

I really hopy this feature is supported, thank you.

**Comment by telesoho** [comment]
@lekoOwO 
Embed base64 image now supported from version  0.13.1.
