### ISSUE TITLE
设置中文路径后 markdown中 路径乱码

### ISSUE THREAD

**Issue by imxood** [telesoho/vscode-markdown-paste-image#39]
中文路径乱码, 这个是否可以修复下呢? 希望可以保存为原样的文字, 不要转义

![image](https://user-images.githubusercontent.com/14890680/113959261-19f41200-9855-11eb-9976-77a4481ff227.png)

![image](https://user-images.githubusercontent.com/14890680/113959334-3f811b80-9855-11eb-9b52-e9f28493f4e2.png)

**Comment by telesoho** [comment]
@imxood 
版本ver 0.13.1 现在支持不转义文件路径了，具体参考MarkdownPaste.encodePath的设定．
