### ISSUE TITLE
files being saved to incorrect location

### ISSUE THREAD

**Issue by mivanit** [telesoho/vscode-markdown-paste-image#42]
When pasting a file, if the path is set to `F:/foo/img/my_image.png`, the image is instead saved to `C:/foo/img/my_image.png`, and the path is also changed to `C:/foo/img/my_image.png`. 

Bug occurs a windows 10 machine, using a fresh install (as of 2021-07-29) of the extension from marketplace.

- dialog box for saving the image
![dialog box for saving the image](https://user-images.githubusercontent.com/19347900/127580677-b1aab3b2-7667-4734-84db-705b4c0b074c.png)

- text pasted into markdown by the extension
![text pasted into markdown by the extension](https://user-images.githubusercontent.com/19347900/127580698-e8d8007b-4392-41fa-931a-c69340cd323f.png)

The image does in fact get saved to the given location.

**Comment by mask2012** [comment]
the same problem happens to me, is there any temp solution? thanks!

**Comment by mask2012** [comment]
another information is, it's working fine about half month ago, and suddenly changed it's action. I'm not sure if it's caused by vscode version update or something else?

**Comment by telesoho** [comment]
While input values contain driver character, vscode.Uri.parse().fsPath will get a file path with no driver character.
Maybe it is a bug:
`
> vscode.Uri.parse("f:/test/images").fsPath 
  '/test/images'
> vscode.Uri.parse("file:///f:/test/images").fsPath
  'f:/test/image' 
`
I have fixed it in new release 0.13.4.
