### ISSUE TITLE
Add WSL support 希望能添加WSL的支持

### ISSUE THREAD

**Issue by JeffersonQin** [telesoho/vscode-markdown-paste-image#43]
具体实现可以看我的这个`PR` (是在`PicGo`的项目)：https://github.com/PicGo/PicGo-Core/pull/87

**Comment by telesoho** [comment]
@JeffersonQin 
谢谢你的帮助。我尝试改改看，但我没有用过WSL，没法去测试。

**Comment by JeffersonQin** [comment]
其实总体思路就是在`shell`中调用`powershell`（毕竟我们已经有`ps`脚本了）
