### ISSUE TITLE
HTML conversion is not working 未能将HTML tag转换为Markdown

### ISSUE THREAD

**Issue by JeffersonQin** [telesoho/vscode-markdown-paste-image#44]
插件版本：v0.13.3

复制内容：

![image](https://user-images.githubusercontent.com/30655701/127760021-e9fdd793-1609-4ba9-93d4-5f2ee1f9659f.png)

输出：

![image](https://user-images.githubusercontent.com/30655701/127760024-6f2a5ba2-3194-4834-8df9-970e380666b5.png)

**Comment by telesoho** [comment]
@JeffersonQin 
转换HTML tag为Markdown的功能没问题呀，你发的图里也没包含html tag。

**Comment by JeffersonQin** [comment]
嘶.... 我是复制的浏览器的内容，理论上剪切板中应该包含HTML tag的（Windows下测试的）

**Comment by JeffersonQin** [comment]
我举个例子：
下图是我复制的内容：

![image](https://user-images.githubusercontent.com/30655701/127777747-c3203036-4133-48ac-b50a-ee37ac30fd6f.png)

下图是剪切板的输出：

![image](https://user-images.githubusercontent.com/30655701/127777759-27061970-93b6-4ec9-a528-e4bdad498985.png)

命令：

```powershell
Get-Clipboard -TextFormatType Html
```

**Comment by telesoho** [comment]
由于我不用Windows和Mac，目前只完成了Linux中把HTML转换为Markdown的功能。我曾经尝试过在Windows中使用powershell去获取剪贴板中的内容，但是当时windows中有一个bug，如果剪贴板内容中有中文或日文字符时，将剪贴板中的文本转换为UTF编码会出现非法字符，导致无法取出正确的剪贴板内容，所以就放弃了。

**Comment by JeffersonQin** [comment]
我找到解决办法了。这两天正好在写WPF，之前也接触过Clipboard类，可以用类似的办法：即，WPF (.NET) 封装好的函数来调Clipboard

代码：
```powershell
Add-Type -Assembly PresentationCore
[Windows.Clipboard]::GetData([Windows.DataFormats]::Html)
```
![image](https://user-images.githubusercontent.com/30655701/127900764-bc2f5d65-5d25-4807-9e4f-b73287fbcdf0.png)

Reference:
- https://docs.microsoft.com/en-us/dotnet/api/system.windows.dataformats?view=net-5.0
- https://www.cnblogs.com/guogangj/p/7465951.html
- https://blog.vichamp.com/2014/07/21/forward-chinese-text-into-clipboard/

**Comment by JeffersonQin** [comment]
您这边不方便用win对吧，这个反正也不急，我过两天有时间研究一下写一下，提个PR上了，到时候麻烦您看一下

**Comment by telesoho** [comment]
@JeffersonQin 
太感谢了！！！

**Comment by lukebrowell** [comment]
Would you consider making the extension handle more complex paste-types, so as to meet with the reporting user's expectations?

Have a look at how [clipboard2markdown](http://euangoddard.github.io/clipboard2markdown/) works.

[Complex Clipboard type handling code](https://github.com/euangoddard/clipboard2markdown/blob/master/clipboard2markdown.js)

[A more detailed explanation of how it works](https://stackoverflow.com/questions/2176861/javascript-get-clipboard-data-on-paste-event-cross-browser/6804718#6804718)

**Comment by telesoho** [comment]
@lukebrowell 
This extension also use [to-markdown](https://github.com/mixmark-io/turndown) lib to convert html to markdown too, but it only work on Linux. Vscode is not a web browser, it seem does not support document.addEventListener API, so it is a troublesome thing to get complex clipboard type in vscode.
