### ISSUE TITLE
command 'telesoho.MarkdownPaste' not found

### ISSUE THREAD

**Issue by bearzyj** [telesoho/vscode-markdown-paste-image#45]
Dear author,

OS: macOS
Plugin version: 0.13.4
VSCode: 1.58.2

After I installed this plugin and tried, just show the error `command 'telesoho.MarkdownPaste' not found`.

So I tried to downgrade to 0.13.3, works well.
Tried to upgrade to 0.13.4 again, the same issue happened.

**Comment by telesoho** [comment]
@bearzyj 
Thank you for reporting this issue. It has been fixed in 0.13.7.

**Comment by johnnycardy** [comment]
I've just downgraded from 1.0.0 to 0.13.7 to get around this issue - tried reinstalling 1.0 but with no luck.
