### ISSUE TITLE
Variable "${workspaceRoot}" looks resolved incorrectly

### ISSUE THREAD

**Issue by bearzyj** [telesoho/vscode-markdown-paste-image#46]
Dear author,

OS: macOS
Plugin version: 0.13.7
VSCode: 1.58.2

When set Path to "${workspaceRoot}/ABC", the actual path is not the workspace root, but still the same level folder with "[object Object]/ABC/"

Please help to take a look

**Comment by telesoho** [comment]
Thank you for reporting issue again.
This bug has been fixed in ver 0.13.8.
