### ISSUE TITLE
command 'telesoho.MarkdownPaste' not found

### ISSUE THREAD

**Issue by fdq09eca** [telesoho/vscode-markdown-paste-image#47]
![image](https://user-images.githubusercontent.com/51902242/132082195-4dcceff6-06b3-4d81-b7a0-b93fb2cf445b.png)

Previously, it still working fine but not today. In particular, the cmd + alt + v keybinding is not working. while it is registered at `default_keybindings.json`, see below 

![image](https://user-images.githubusercontent.com/51902242/132082267-86a61f07-6def-4f7a-a605-3707b88973ef.png)

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.6.0

**Comment by telesoho** [comment]
@fdq09eca 
You can toggle vscode develop tools on and try to use telesoho.MarkdownPaste again  to see what's going on with the extension like this:

![image](https://user-images.githubusercontent.com/10979091/132098572-8faa5fd5-5fc7-4cad-87ce-9c065adbada8.png)

**Comment by fdq09eca** [comment]
![image](https://user-images.githubusercontent.com/51902242/132104784-ee6560a0-7dc1-450e-b172-a1d0ad577a7d.png)

**Comment by telesoho** [comment]
@fdq09eca 
You installed extension is ver 0.13.6, please update it to lastest ver 0.13.8, then try again.

**Comment by fdq09eca** [comment]
> @fdq09eca
> Your installed extension is ver 0.13.6, please update it to lastest ver 0.13.8, then try again.

Work perfectly.  Thanks.
