### ISSUE TITLE
Doesn't work on Fedora 35

### ISSUE THREAD

**Issue by marcinjahn** [telesoho/vscode-markdown-paste-image#49]
I've just installed the extension in VS Code. It doesn't seem to work at all on my system. I'm using Fedora 35.

**Comment by telesoho** [comment]
@marcinjahn 
The extension need xclip to get clipboard, Did you installed it?

**Comment by marcinjahn** [comment]
You're right! Somehow I was sure I had it. Obviously I did not. Thanks!
