### ISSUE TITLE
Enable 'invalid' filenames

### ISSUE THREAD

**Issue by LemuelCushing** [telesoho/vscode-markdown-paste-image#5]
First, I want to thank you for taking on this wonderful little extension - it's superbly useful and the small changes you've made are really well done.

One issue/request, though - not sure what the criteria for a valid filename are, but it seems to be all lower caps, which seems a bit too strict. I currently have to manually input the name due to this restriction, and it'd be great if it could be optional.

While we're at it, having a default storage instead of prompting for a path each time would also be a nice option to opt-in to, but it's a minor thing.

Once again, thanks!

**Comment by LemuelCushing** [comment]
Hope you don't mind - I'll list a few other small issues here, more for me than anything - I hope to try and give it a go at some point soon, even if my JS skills are quite modest. 

* Enable prefixing the path pasted, (`![](./Pics/file.PNG)` instead of `![](Pics/file.PNG)`) 
* Auto camelCase/snake_case selected string into file name (And perhaps add the original to the `[alt]` field?)
* Add the pasted file path to the clipboard
* Add textile format 

Really hope it ain't an out of line use of this medium - just some small ideas I'd be glad to try and tackle if and when I find the time to try, or, of course, I'll be grateful if were added, one way or another.

**Comment by telesoho** [comment]
Thank you for your help.
I have fixed it. you can use uppercase character as filename now.
Also, I have add pasteImage.silence config option to enable/disable showing confirm box while paste image. Set pasteImage.silence=true in your config file, the pasted file will be save in default storage with no prompting.

**Comment by LemuelCushing** [comment]
Wonderful, thank you!
