### ISSUE TITLE
Support for pasting code with auto detecting language

### ISSUE THREAD

**Issue by pluveto** [telesoho/vscode-markdown-paste-image#50]
Paste code fences with language (can be infer from code)

**Comment by telesoho** [comment]
@pluveto 
Thank you for your advice, But infer language from code is not easy.

**Comment by pluveto** [comment]
This may be useful: https://github.com/ts95/lang-detector

**Comment by telesoho** [comment]
@pluveto 
Thank you very much.
I found microsoft has already used  language detection in vscode.
https://github.com/microsoft/vscode-languagedetection
I will try to use it in this extension.

**Comment by pluveto** [comment]
> @pluveto Thank you very much. I found microsoft has already used language detection in vscode. https://github.com/microsoft/vscode-languagedetection I will try to use it in this extension.

Wow, that's awesome!

**Comment by telesoho** [comment]
@pluveto 
I already add this feature in new version v0.14.0 (command: Markdown Paste Code)

**Comment by pluveto** [comment]
Nice work!
