### ISSUE TITLE
Latest changes broke image pasting on macOS

### ISSUE THREAD

**Issue by marcinjahn** [telesoho/vscode-markdown-paste-image#58]
Since the last update I cannot paste images into markdown anymore on macOS Monterey.
I see the following logs:

```log
[12-26 17:27:01] Cannot found script for darwin
[12-26 17:27:01] getClipboardContentType
[12-26 17:27:01] null
```

A couple days ago it worked perfectly fine.

**Comment by knyzorg** [comment]
Mea culpa. I have accidentally removed support for it in #54 by removing [this codepath](https://github.com/telesoho/vscode-markdown-paste-image/pull/54/files#r775273775).

It will be fixed in a few minutes.

**Comment by knyzorg** [comment]
@marcinjahn 

You can test the fix by running

```bash
git clone https://github.com/knyzorg/vscode-markdown-paste-image
cd vscode-markdown-paste-image
npm i
npx vsce package
code --install-extension ./vscode-markdown-paste-image-0.15.2.vsix
```

**Comment by marcinjahn** [comment]
@knyzorg The error is a bit different now:

```log
12-26 20:03:01] "vscode-markdown-paste" is now active!
[12-26 20:03:01] No scipt exists for darwin
[12-26 20:03:01] Clipboard Type:
[12-26 20:03:01] -1
[12-26 20:03:04] /Users/marcin/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.15.2/res/mac.applescript: /Users/marcin/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.15.2/res/mac.applescript: cannot execute binary file
```

**Comment by knyzorg** [comment]
What happens when you try running `osascript /Users/marcin/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.15.2/res/mac.applescript`? Do you encounter the same error?

**Comment by marcinjahn** [comment]
```sh
~/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.15.2/res
❯ osascript /Users/marcin/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.15.2/res/mac.applescript


~/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.15.2/res
```

It executes properly (I passed no arguments like in your example).

**Comment by knyzorg** [comment]
@telesoho Do you have a macbook you can test with? I'm not sure why this is happening.

**Comment by marcinjahn** [comment]
@knyzorg I think there is some issue with the choice of executor. I logged the `${shell} ${options.join(" ")}` line of 
 the `runCommand` function. I got `sh /Users/marcin/.vscode/extensions/telesoho.vscode-markdown-paste-image-0.15.2/res/mac.applescript /Users/marcin/tmp/2021-12-26-20-20-59.png`. It should use `osascript` instead of `sh` I guess.

**Comment by knyzorg** [comment]
@marcinjahn I did some changes. Can you pull and try again?

**Comment by marcinjahn** [comment]
@knyzorg Yes, that works. Actually, I started creating a branch with that fix, but you were faster. Also, you fixed more switch cases than that single place.

**Comment by marcinjahn** [comment]
@knyzorg Even though the functionality works, the log is a bit confusing:

```log
[12-26 20:37:32] "vscode-markdown-paste" is now active!
[12-26 20:37:32] No scipt exists for darwin
[12-26 20:37:32] Clipboard Type:
[12-26 20:37:32] -1
```

"No script exists"?

**Comment by knyzorg** [comment]
The way this extension is designed, it expects to have multiple scripts for each OS.

On for 
 - Detecting clipboard types
 - Pasting images
 - Pasting rich text
 - Pasting plain text

The only one we have for Mac is pasting images. So the way it works is it fails detect the clipboard type for Mac and falls back to attempting to extract plain text, which if fails, runs the paste image script.

I'm not very good with Macs, so someone will need to write the other scripts.

**Comment by marcinjahn** [comment]
Yeah, I see that in code. I'm not good neither, today was the first time I saw actual AppleScript code :)

**Comment by knyzorg** [comment]
The fix has been merged

**Comment by JeffersonDing** [comment]
Having the same issue on macOS Monterey on version 0.18.6. Copy past image works as expected but download image results in output
```
[04-01 00:24:05] "vscode-markdown-paste" is now active!
[04-01 00:24:05] No scipt exists for darwin
[04-01 00:24:05] Clipboard Type:
[04-01 00:24:05] -1
```
