### ISSUE TITLE
could you please make this extension works for vs code online or github codespace?

### ISSUE THREAD

**Issue by chenxizhang** [telesoho/vscode-markdown-paste-image#63]
RT

**Comment by knyzorg** [comment]
When the VSCode allows us first-class clipboard access, yes. Right now, no.

Blocked on: https://github.com/microsoft/vscode/issues/139761

**Comment by chenxizhang** [comment]
> When the VSCode allows us first-class clipboard access, yes. Right now, no.
> 
> Blocked on: [microsoft/vscode#139761](https://github.com/microsoft/vscode/issues/139761)

Thanks for the reply
