### ISSUE TITLE
Feature Request: Will your extension support folder `.vscode/settings.json` on a workspace? 

### ISSUE THREAD

**Issue by gusbemacbe** [telesoho/vscode-markdown-paste-image#64]
Hello!

On a specific project with a folder `.vscode` on a workspace, I would not like to add `MarkdownPaste.path` setting to the global user settings, because it would be boring to always change the path in `MarkdownPaste.path` at the global user setting. 

For example, on a global user `settings.json`:

```json
{
  "MarkdownPaste.path": "${fileDirname}/blabla/images/"
}
```

On a specific project's folder containing `.vscode/settings.json`:

```json
{
  "MarkdownPaste.path": "${fileDirname}/blabla/assets/images/examples"
}
```

When I press `Ctrl/Cmd` + `Alt` + `V`, I have to rename and type always `assets/images/examples`, because of `"MarkdownPaste.path": "${fileDirname}/blabla/images/"`, but I find it too tired, and it is not supported for folder settings on a workspace. I do not want to apply `"MarkdownPaste.path": "${fileDirname}/blabla/assets/images/examples"` to the global user settings, because it is for the specific project and not for all projects. 

You can analyse the screenshot, observing the tree:

![image](https://user-images.githubusercontent.com/2257024/147899611-11d94707-4c39-499d-b6ee-9468f1f69b46.png)

**Comment by telesoho** [comment]
@gusbemacbe 

https://code.visualstudio.com/docs/getstarted/settings

![image](https://user-images.githubusercontent.com/10979091/147920910-a336837a-41a5-40ca-a1d5-49e81708a1cd.png)

According to Microsoft's documentation, the workspace settings will always override the user's public settings. If you don't want workspace setting, you will remove it.

**Comment by gusbemacbe** [comment]
> According to Microsoft's documentation, the workspace settings will always override the user's public settings. If you don't want workspace setting, you should remove it.

I do not mean the workspace settings; I want to override the user settings with a project root folder (`.vscode/settings.json`). But your extension does not support to override the project root folder **on a workspace** with the user settings. 

Only **on an explorer** (without workspace), your extension supports to override the project root folder settings with the user settings.

Compare that image above (with workspace) with the image below (without workspace):

![image](https://user-images.githubusercontent.com/2257024/147929599-a9c1e1ce-5308-4d3b-a1a4-cf6eb5463257.png)

You can see "Open Folder" (your extensions supports) and "Add Folder to Workspace" (your extension does not support):

![image](https://user-images.githubusercontent.com/2257024/147930223-0a5304b9-b247-47a6-b64b-fa7ae1149b4c.png)

Remember not to confound project root folder containing `.vscode/settings.json` with Workspace settings.

You can see how @valentjn's [vscode-ltex](https://github.com/valentjn/vscode-ltex) supports project root folder settings **both** with or without a workspace. You can see the image above that `"ltex.language": "pt-PT"` is enabled at `.vscode/settings.json` on a project on a workspace. Yours is not enabled because your extension does not support.

**Comment by gusbemacbe** [comment]
It works fully. Impeccable!

![image](https://user-images.githubusercontent.com/2257024/147994560-2de653c9-a069-4335-8d18-6fee5e82edba.png)
