### ISSUE TITLE
Fix encoding problem in non-english language in Windows os

### ISSUE THREAD

**Issue by huhk-sysu** [telesoho/vscode-markdown-paste-image#7]
I'm using your extension, which has saved me much time.

Everything is fine before I tried to use it when the Markdown file was in a folder with Chinese letter in its name, which means **the `imagePath` below may contain Chinese letter**.

```typescript
private static saveClipboardImageToFileAndGetPath(imagePath, cb: (imagePath: string) => void)
```

I traced the execution of your extension and found the Chinese part of `imagePath` became a mess in the callback function of `saveClipboardImageToFileAndGetPath`:

![image](https://user-images.githubusercontent.com/14769033/29682535-f0511d78-893d-11e7-81e5-95cc8dc06adb.png)

According to your code, when `plplatform === 'win32'`, it will run the `/res/pc.ps1` file with `PowerShell`.
And in the file `pc.ps1`, the output is exactly the input, without any modification.

```powershell
param($imagePath)

......

$imagePath
```

After some search I found [this article](https://blogs.msdn.microsoft.com/powershell/2006/12/11/outputencoding-to-the-rescue/), which says

> When we pipe output data from PowerShell cmdlets into native applications, the output encoding from PowerShell cmdlets is controlled by the $OutputEncoding variable, which is by default set to ASCII

And that's the problem, Chinese letters(and also letters in many other languages) can't be represented in ASCII encoding, so the `data.toString()` in following code can't get the correct `imagePath`.

```typescript
powershell.stdout.on('data', function (data: Buffer) {
    cb(data.toString().trim());
});
```
AFAIK there's two way to fix the problem:

- The first way. Since you don't modify the `imagePath` in file `pc.ps1`,  the code can be rewritten like this:

```typescript
powershell.on('exit', function (code, signal) {
    cb(imagePath)
 });
powershell.stdout.on('data', function (data: Buffer) {
    // do nothing
});
```
- The second way. Add a line to adjust the encoding of output. This will set the output of `pc.ps1` to UTF-8, which can represent many letters in various language.

```powershell
param($imagePath)

......

[System.Console]::OutputEncoding=[System.Text.Encoding]::GetEncoding(65001)
$imagePath
```

Thanks for your work!

**Comment by telesoho** [comment]
Thank you very much for your help.
I had try your second way to fix this bug, but not work.
Because using $imagePath directly always get ASCII output.  I found [this answer](https://stackoverflow.com/questions/22349139/utf-8-output-from-powershell), so I use the following code to fix this bug. 
```
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::WriteLine($imagePath)

```
