### ISSUE TITLE
markdown img syntax isn't used in mdx files

### ISSUE THREAD

**Issue by chrisolsen** [telesoho/vscode-markdown-paste-image#70]
It seems that the extension doesn't recognize the mdx* file as the same as an .md file and therfore doesn't add the markdown img syntax to the url, so when I execute the extension all I get is a path string ex. `.images/2022-02-03-12-23-39.png`

*An mdx file is a Markdown (.md) file that includes elements of JavaScript XML 

**Update**: Turns out it is the language mode that is causing the issue not the extension -> Markdown vs Markdown React

**Comment by knyzorg** [comment]
This can be fixed by updating this check:  https://github.com/telesoho/vscode-markdown-paste-image/blob/020fe225a4ecdd21b62a8794c6f3df9de435e16a/src/paster.ts#L341

**Comment by telesoho** [comment]
> This can be fixed by updating this check:
> 
> https://github.com/telesoho/vscode-markdown-paste-image/blob/020fe225a4ecdd21b62a8794c6f3df9de435e16a/src/paster.ts#L341

I have removed the check.

**Comment by telesoho** [comment]
@chrisolsen 
This extension support another language mode now, Please check #56
