### ISSUE TITLE
FeatReq: Mac Support for Rich Text Paste

### ISSUE THREAD

**Issue by PabloLION** [telesoho/vscode-markdown-paste-image#74]
I saw your fancy "Paste smart" feature and noticed it works really well.
Is it possible to make this supports Mac? I downloaded this repo and try to PR it but I don't know where to start. Could you point that out for me (in case if you are not going to do that)? I saw [Obsidian](obsidian.md) has this function.
Thanks.

**Comment by PabloLION** [comment]
BTW my current work around is to paste the rich text in an empty file in [Obsidian](obsidian.md), then cut-paste from there. Or using it to open a same file.

**Comment by PabloLION** [comment]
Also this one works for Win/Linux but not for macOS
https://marketplace.visualstudio.com/items?itemName=d3v.pastespecial

**Comment by telesoho** [comment]
@PabloLION 
> Yes. That's why I made issue here first. Can I know what make it difficult to make an macOS version?
Because I don't have a mac.

**Comment by PabloLION** [comment]
Can you tell me where to start? Or maybe add a contribution guide in README?

**Comment by PabloLION** [comment]
Thanks! This is very detailed. I'll try to make a PR later since I've finished my work on Docs and moving on to the next part. I think we can either close this issue or keep it open since other might help.
I'll let you to decide.
