### ISSUE TITLE
Windows: GIF are always saved to C:\

### ISSUE THREAD

**Issue by JimLeon595** [telesoho/vscode-markdown-paste-image#76]
i have the same paste problem that the plugin shows the correct path while pasting the gif image (e.g. D:/test/xxx.gif). But the image gets stored on the C:/test/xxx.gif drive instead. Also the created link directs to C:/.

 Here is the screenshots to show the error.

![image](https://user-images.githubusercontent.com/16500142/156601341-d9af66ee-93c0-45ba-89c3-b83884c6f722.png)

 Best regards,
Lukas

P.S.: Thanks by the way for this great plugin

**Comment by telesoho** [comment]
@JimLeon595 
What version you are using?

**Comment by JimLeon595** [comment]
> @JimLeon595 如果粘贴图像会发生什么？你能告诉我扩展版本吗？
I press ctrl + alt +v to paste gif to my article (e.g. W:/test/xxx.gif),but its always change my path to C:/test/xxx.gif,though the gif picture download in the right path ,but my acticle cant show the gif properly
and my version is v0.18.5

**Comment by telesoho** [comment]
@JimLeon595 

就是说无论你是用Markdown Paste(Ctrl+Att+V)还是Markdown Download(Ctrl+Alt+D)，图片保存的位置是对的，只是插入到Markdown里的链接是错的，是吗？

**Comment by JimLeon595** [comment]
是的是的，哈哈哈，不好意思，我的工地英文

Markdown Paste(Ctrl+Att+V)刚刚我去尝试了一下，应该还是和原版的Markdown一样，无法直接复制gif粘贴，需要我们自己构建![](xxx.gif)才能进行显示，如下图，本地 gif Markdown Paste 之后会格式被改成`PNG` 

![image](https://user-images.githubusercontent.com/16500142/156722340-747dad84-494f-4b2d-a7c4-0a0c71788734.png)


Markdown Download(Ctrl+Alt+D)只要下载的GIF图片不是放在C盘的路径上，然后他插入的位置，无论盘符是什么都会被切换为`C:`，如下图

![image](https://user-images.githubusercontent.com/16500142/156722085-496bf0b9-3895-4388-8b75-2219700b08b6.png)

**Comment by telesoho** [comment]
@JimLeon595 

> 
> Markdown Paste(Ctrl+Att+V)刚刚我去尝试了一下，应该还是和原版的Markdown一样，无法直接复制gif粘贴，需要我们自己构建![](xxx.gif)才能进行显示，如下图，本地 gif Markdown Paste 之后会格式被改成`PNG`
> 
> ![image](https://user-images.githubusercontent.com/16500142/156722340-747dad84-494f-4b2d-a7c4-0a0c71788734.png)
> 

我想知道的是，用Markdown Paste粘贴的时候，图片是否被保存到了正确的路径下，比如图中的：`d:/Test/2022-03-04-15-54-15.png`是否被正确的保存到了`d:/Test/`下，然后生成的Markdown链接是否正确。

> Markdown Download(Ctrl+Alt+D)只要下载的GIF图片不是放在C盘的路径上，然后他插入的位置，无论盘符是什么都会被切换为`C:`，如下图
> 
> ![image](https://user-images.githubusercontent.com/16500142/156722085-496bf0b9-3895-4388-8b75-2219700b08b6.png)
> 
> 而且这个问题的本质是针对GIF这种图片格式来说的，对于我来说，jpg，png等静态图片暂时还没遇到过相同的问题

从图里看，如果使用Markdown Download 下载图片的时候，插入Markdown的链接变成了C:，我想知道的是图片文件是被保存到了d:/Test下，还是c:/Test下，或者根本没有保存文件。

实在不好意思，我没有Windows系统，自己无法做测试，只能不停的麻烦你了。

**Comment by telesoho** [comment]
问题可能出在这里：

https://github.com/telesoho/vscode-markdown-paste-image/blob/8bcb68beb25425fff7469cbb1f2324fbd1613a92/src/paster.ts#L576
