### ISSUE TITLE
can not be active by push 'ctrl+alt+v'

### ISSUE THREAD

**Issue by morning-start** [telesoho/vscode-markdown-paste-image#77]
when I reload my vscode, I can not activate this extension just by "ctrl+alt+v", it must use command palette to start.

**Comment by telesoho** [comment]
@morning-start 

Please check your Keyboard Shortcuts setting.

![image](https://user-images.githubusercontent.com/10979091/156763031-613718f5-8cfe-429c-bccc-0709c17c07e0.png)

**Comment by morning-start** [comment]
I just hava only one hot key of "ctrl alt v" as bellow.

more infomation: it just can not active extension by hot key. After activation, it can work well.

![image](https://user-images.githubusercontent.com/76601464/156763665-a84b4b3d-ac8e-4d2b-b4fe-afcea40c2b47.png)

**Comment by morning-start** [comment]
> @morning-start
> 
> Please check your Keyboard Shortcuts setting.
> 
> ![image](https://user-images.githubusercontent.com/10979091/156763031-613718f5-8cfe-429c-bccc-0709c17c07e0.png)
