### ISSUE TITLE
macOS Monterey image download doesn't work

### ISSUE THREAD

**Issue by JeffersonDing** [telesoho/vscode-markdown-paste-image#80]
Image pasting works as usual, download doesn't work.
Output from VSCode
```
[04-01 00:24:05] "vscode-markdown-paste" is now active!
[04-01 00:24:05] No scipt exists for darwin
[04-01 00:24:05] Clipboard Type:
[04-01 00:24:05] -1
```

**Comment by JeffersonDing** [comment]
[Pull request](https://github.com/telesoho/vscode-markdown-paste-image/pull/81) for my temporary fix.

**Comment by telesoho** [comment]
@JeffersonDing 
Thank you for your PR.
But the new `ClipboardType.Apple` confuse me. Maybe we need a mac script to get correct clipboard type(text, html, or image) first.

**Comment by JeffersonDing** [comment]
> @JeffersonDing 
> 
> Thank you for your PR.
> 
> But the new `ClipboardType.Apple` confuse me. Maybe we need a mac script to get correct clipboard type(text, html, or image) first.

Of course. It's just a temp fix for myself and incase anyone wants to make it work for now. I'll see if there's a more elegant way to make a clipboard type script.

**Comment by telesoho** [comment]
@JeffersonDing 
I have release a new version v0.19.0 from your PR. If no any problem we can close this issue
