### ISSUE TITLE
粘贴URL生成的链接有问题

### ISSUE THREAD

**Issue by PascalZh** [telesoho/vscode-markdown-paste-image#87]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/32212800/170811173-f6cd10a4-4b61-41c9-9fef-8af2da1ed934.png">

如图所示，第一个是手动改对的，第二个是按Ctrl+Alt+V生成的。

**Comment by PascalZh** [comment]
链接是复制了EDGE浏览器的地址栏，开启了Edge的这个功能：https://support.microsoft.com/en-us/microsoft-edge/improved-copy-and-paste-of-urls-in-microsoft-edge-d3bd3956-603a-0033-1fbc-9588a30645b4

**Comment by telesoho** [comment]
只有粘贴中文内容的时候才会出现这个问题。
https://github.com/telesoho/vscode-markdown-paste-image/blob/2585ad16fbe7591946f4b5ffb3e6e7b610334dc2/res/scripts/win32_get_clipboard_text_html.ps1#L4-L8

这里做了一个正则表达式替换，问题可能在这里。
