### ISSUE TITLE
Variable expansion in MarkdownPaste.namePrefix not working

### ISSUE THREAD

**Issue by stevenengland** [telesoho/vscode-markdown-paste-image#89]
Hi, I would like to use to use vscode variables like `${relativeFileDirname}` to prepend or append it to my filenames. But the expansion simply does not work. Should it? Like in `MarkdownPaste.path` where `${fileDirname}` is used by default.

Setting `"MarkdownPaste.namePrefix": "${workspaceFolderBasename}_"`, gives` /path/to/current/dir/${workspaceFolderBasename}_xyz.png`

**Comment by telesoho** [comment]
@stevenengland 
The `workspaceFolderBasename` predefine variable not supported.
Please see:
https://github.com/telesoho/vscode-markdown-paste-image#config
