### ISSUE TITLE
command 'extension.MarkdownPaste' not found

### ISSUE THREAD

**Issue by zhuangyin8** [telesoho/vscode-markdown-paste-image#9]
![image](https://user-images.githubusercontent.com/20805894/31807427-a12fb788-b5a0-11e7-8c92-3aac636d4b65.png)

**Comment by telesoho** [comment]
@zhuangyin8 
I think the extension has not been installed successfully on your machine.
You can check it by the following steps:
1. Press CTRL+SHIFT+P  and input "Markdown Paste".
2. If "Markdown Paste" command not been shown in the command list. Please reinstall the extension once again.
3. If it doesn't work after reinstalling. Could you tell me more detail about your machine (Visual Studio Code version & OS)?
 
我猜测你应该能看得懂中文：
我猜测原因是可能是插件没有被正确安装。按下CTRL+SHIFT+P，输入“Markdown Paste"，检查一下“Markdown Paste"命令是否被显示出来了？如果没有，请重新安装一下这个插件。重新安装后，仍然不能用，麻烦你告诉我一下你所用的是什么VSCODE的版本和操作系统么？

**Comment by zhuangyin8** [comment]
![Markdown Pastes](https://user-images.githubusercontent.com/20805894/31846317-88a974fa-b63c-11e7-8733-51df704ebc71.gif)

**Comment by telesoho** [comment]
You can try to run "Clear Command History".

https://www.roelvanlisdonk.nl/2017/07/14/fix-error-command-o-pickprojectandstart-not-found-in-visual-studio-code/

**Comment by telesoho** [comment]
@zhuangyin8 
Do you give me more detail about it?
There are no another users report this bug as yet. If you no any hint, I will close this issues.
