### ISSUE TITLE
How to customize the format of ${datetime} ?

### ISSUE THREAD

**Issue by m2acgi** [telesoho/vscode-markdown-paste-image#91]
How to customize the format of `${datetime}` like `yyyy-MM-DD_HH-mm-ss` ? Thanks!

**Comment by telesoho** [comment]
@m2acgi 
You can customize the format by ${datetime|yyyy-MM-DD_HH-mm-ss}  in new version 0.19.3 now.

**Comment by m2acgi** [comment]
Perfect! Thanks! 👍
