### ISSUE TITLE
need a variable such as ${fileDirName}.replace(${workspace}, "")

### ISSUE THREAD

**Issue by anonymousALLDAY** [telesoho/vscode-markdown-paste-image#93]
for example, let   `C:/project/a/b/c/d.md` 

then here `${workspaceRoot}` might be `C:/project` if I opened the folder `project` in vscode

and `${fileDirName}` might be `C:/project/a/b/c`

then I only want to get `a/b/c` part.

**Comment by telesoho** [comment]
@anonymousALLDAY 
You can use ${relativeFileDirname} in v0.19.4.
